#define _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING

#include "main.cpp"
#include "Animator.cpp"
#include "Audio.cpp"
#include "Background.cpp"
#include "Ball.cpp"
#include "Collider.cpp"
#include "CollisionDetection.cpp"
#include "ConfigManager.cpp"
#include "Entity.cpp"
#include "Game.cpp"
#include "Input.cpp"
#include "Level.cpp"
#include "Player.cpp"
#include "Spline.cpp"
#include "Util.cpp"
#include "rendering/Color.cpp"
#include "rendering/Mesh.cpp"
#include "rendering/Renderer.cpp"
#include "rendering/Shaders.cpp"
#include "rendering/Texture.cpp"

// Third party libraries
#include "imgui/imgui.cpp"
#include "imgui/imgui_widgets.cpp"
#include "imgui/imgui_draw.cpp"
#include "imgui/imgui_impl_sdl.cpp"
#include "imgui/imgui_impl_opengl3.cpp"